// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/enkazu1116/go_home/internal/domain"
	"github.com/enkazu1116/go_home/internal/handler"
	"github.com/enkazu1116/go_home/internal/repository"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp はアプリケーション全体の依存関係を初期化する関数
func InitializeApp(db *gorm.DB) (*App, error) {
	timeIsMoneyGormRepo := repository.NewTimeIsMoneyRepository(db)
	userUsecase := domain.NewUserUsecase(timeIsMoneyGormRepo)
	userHandler := handler.NewUserHandler(userUsecase)
	app := NewApp(userHandler)
	return app, nil
}

// wire.go:

// App はアプリケーション全体を表す構造体
type App struct {
	UserHandler *handler.UserHandler
}

// NewApp はアプリケーション全体の構造体を作成する
func NewApp(userHandler *handler.UserHandler) *App {
	return &App{
		UserHandler: userHandler,
	}
}
